/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function defaultConductorConfig(adminPort: number, conductorEnvironmentPath: string, keystoreConnectionUrl: string, bootstrapServerUrl: string, signalingServerUrl: string, allowedOrigin: string): string
export function happBytesWithCustomProperties(happPath: string, properties: Record<string, string | undefined | null>): Promise<Array<number>>
export function saveHappOrWebhapp(happOrWebHappPath: string, uisDir: string, happsDir: string): Promise<string>
/** Checks that the happ or webhapp is of the correct format */
export function validateHappOrWebhapp(happOrWebhappBytes: Array<number>): Promise<string>
export interface KeyFile {
  rootSeed: string
  revocationSeed: string
  deviceSeedsSeed: string
  revocationKey0: string
  deviceSeed0: string
  timestamp: number
}
/**
 * Generates root seed, revocation key and device seed
 *
 * Use a single passphrase for the whole file for starters
 */
export function generateInitialSeeds(passphrase: string): Promise<KeyFile>
export interface ZomeCallUnsignedNapi {
  cellId: Array<Array<number>>
  zomeName: string
  fnName: string
  payload: Array<number>
  capSecret?: Array<number>
  provenance: Array<number>
  nonce: Array<number>
  expiresAt: number
}
export interface ZomeCallNapi {
  cellId: Array<Array<number>>
  zomeName: string
  fnName: string
  payload: Array<number>
  capSecret?: Array<number>
  provenance: Array<number>
  nonce: Array<number>
  expiresAt: number
  signature: Array<number>
}
export type JsMossLairClient = MossLairClient
export class MossLairClient {
  constructor()
  static connect(connectionUrl: string, passphrase: string): Promise<MossLairClient>
  signZomeCall(zomeCallUnsignedJs: ZomeCallUnsignedNapi): Promise<ZomeCallNapi>
  importLockedSeedBundle(importLockedSeedBundle: string, passphrase: string, tag: string): Promise<string>
}
export type JsWeRustHandler = WeRustHandler
export class WeRustHandler {
  constructor()
  static connect(keystoreUrl: string, passphrase: string): Promise<WeRustHandler>
  signZomeCall(zomeCallUnsignedJs: ZomeCallUnsignedNapi): Promise<ZomeCallNapi>
}
